In [2]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [1]:
import numpy as np
data = [1,2,3]
arr =np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
result = arr * 10
result

array([10, 20, 30])

In [5]:
data2d = [
    [1,2,3], [4,5,6], [7,8,9]
]
data2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
arr2 = np.array(data2d)
print(arr2)
print("---")
print(arr2[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[1 4 7]
